### ISSUE TITLE
US15 - Company details

### ISSUE THREAD

**Issue by clara-lancelle** [clara-lancelle/bas#27]
**Coeur de page :** 

- [x] logo (large)
- [x] lien
- [x] point clé avec picto (activité principale, ..)
- [x] sections présentation
- [x] section réseaux sociaux
- [x] section Photos avec zoom 
BONUS - carrousel lightbox

**Colonne de droite**

- [x] logo (large)
- [x] section situation
- [x] carte + lien situer sur une carte
- [ ] section nous joindre
- [ ] section contact 

**Parie basse**

- [x] section "offres de stages proposées" 
- [x] section "offres en alternances proposées"

**Comment by MDW-Guillaume** [comment]
1. section réseaux sociaux
Manque les réseaux en base

2. point clé avec picto (activité principale, ..)
Manque le CA en base

3.  section situation
Manque complément d'adresse

4. section nous joindre
Manque récupération des comptes administrateurs entreprise

5.  section "offres de stages proposées" / section "offres en alternances proposées"
Manque lien / paramètre API pour récupérer les offres de l'entreprise
