### ISSUE TITLE
US09 - INTE MAQUETTE - navbar & footer

### ISSUE THREAD

**Issue by clara-lancelle** [clara-lancelle/bas#4]
- [x] accueil
- [x] offres (sous item "offre de stage" & "offre d'alternance")
- [x] demandes (sous item "demande de stage" & "demande d'alternance") (pas lié dans ce sprint)
- [x] entrprises
- [x] etudiants (pas lié dans ce sprint)
- [x] se connecter (pas lié dans ce sprint)
- [x] creer un compte (pas lié dans ce sprint)

![image](https://github.com/clara-lancelle/api_bas/assets/107240978/20e741ff-f11b-4bb6-a84a-b7fe1174a9aa)

US9

**Comment by MDW-Guillaume** [comment]
header terminé sans les liens
