### ISSUE TITLE
US21 - Student - profile edition

### ISSUE THREAD

**Issue by clara-lancelle** [clara-lancelle/bas#57]
US21 : en tant que candidat connecté je peux éditer/compléter mon profil complet en
cliquant sur « Mon profil ».
Je retrouve tous les champs de l’US 20 qui restent modifiables (en contrôlant tout de même l’unicité du email et du tel mobile).

- [ ] Parmi les champs optionnels proposés, on affiche :
  
  -Photo de profil
  -Adresse du site perso (portfolio, book, depot git)
  -Lien vers la page Linkedin
  -Permis de conduire (case à cocher)
  -Forme de handicap (case à cocher)
  -Compétences (multi select tags)
  -Langues et niveaux
  -Expériences pro
  -CV (upload, max 20 Mo, PDF)

**Comment by MDW-Guillaume** [comment]
Edition terminée, impossible de modifier les langues ainsi que les expériences pour le moment.
Les compétences se modifient mais les noms ne s'affichent plus en sortie de formulaire.
Formulaire grisé
